### ISSUE TITLE
주제 선정

### ISSUE THREAD

**Issue by JSL107** [JSL107/Team7#1]
🐶 @yeeahG  예지님
[](https://www.airbnb.co.kr/rooms/39980455?source_impression_id=p3_1647854088_SL5SKL9VbMbYxU6T)

1. 케이크 집 사이트 - 오늘의 케이크 목록, 케이크 선택, 주문,취소, 회원 가입, 로그인, 클래스 예약
2. 미술관 온라인 - 작품 전시와 전시회 예매, 일정 검색, 작품 구매, 작품 등록

🦊  @JSL107 준석님

1. 에어 비엔비와 비슷한 호텔 예약 사이트 - 로그인, 추천, 회원 가입, 숙박 예약/취소
    
airbnb : 
(https://www.data.go.kr/data/15024675/openapi.do)](https://www.airbnb.co.kr/rooms/39980455?source_impression_id=p3_1647854088_SL5SKL9VbMbYxU6T)

활용 API : [https://www.data.go.kr/data/15024675/openapi.do[](https://www.data.go.kr/data/3068728/openapi.do)](https://www.data.go.kr/data/15024675/openapi.do)

네이버 API 지도

실시간 인기 검색량

🐱  @BANCHEOLJUN  철준님

요즘 관심사와 이슈에 대한 것을 다뤄보는 것은 어떨까!

1. 전기 충전소 위치 정보 시스템 -지도로 띄워서 근처 충전 가능 장소 : 최근 검색, 즐겨 찾기(DB)

활용 API : [https://www.data.go.kr/data/3068728/openapi.do[](https://www.data.go.kr/tcs/dss/selectApiDataDetailView.do?publicDataPk=15099050)](https://www.data.go.kr/data/3068728/openapi.do)

1. 코로나 관련 의료 기관 정보 서비스 시스템 - 달력을 이용하여 예약 및 검사 가능 여부

활용 API : [https://www.data.go.kr/tcs/dss/selectApiDataDetailView.do?publicDataPk=15099050](https://www.data.go.kr/tcs/dss/selectApiDataDetailView.do?publicDataPk=15099050)

🦁 @KimEunhyuk  은혁님

1. 기능적으로 검색, 구매, 카운팅, 인기 품목, 실시간 인기 검색어, 평점 시스템

**Comment by JSL107** [comment]
airbnb로 주제 선정 완료

**Comment by BANCHEOLJUN** [comment]
깔끔하게 인정 . . . . . . . .ㅎ ; .ㅎ;. ;ㅎ.ㅎㅎㅎㅎ
